### ISSUE TITLE
Switching Platform target, configurations issues

### ISSUE THREAD

**Issue by Mattiademasi** [AR-Eye-Tracking-Toolkit/ARETT#12]
Hi,

I would like to test ARETT on a different Headset, though I see that a good part of the codes targets UWP.
In particular, how can I make ARETT work with an Android device?

In the configuration scripts, many things access Windows specific features.

Best regards,
Mattia Demasi

**Comment by sekapp** [comment]
Hi,

the only scripts directly targeting/requiring UWP/HoloLens are the FileHandlerUWP and DataAccessUWP scripts. All other scripts are independent from UWP, eventhough they may contain comments hinting at UWP/HoloLens as this was my main target platform.
While the configuration scripts might also target UWP they are simply a helper and not required for ARETT to function. Therefore you can simply remove the UWP parts or replace them with e.g. Android specific code.

If you want to adapt ARETT for other platforms you should primarly create a custom DataAccess script, based on the UWP script (or the DataAccessEditor script). This script needs to implement the IDataAccess interface. After creating the data access script you add it to the DataProvider using compiler flags (see e.g. line 244 in the DataProvider).
The file handler is optional as you can use the default file handler which should be compatible on all Unity platforms. However, you are free to create your own platform specific handler.
If the eye tracker integrated into your device provides other or additional data compared to the eye tracker in the HL2, you might also want to extend the GazeAPIData class (and all following classes) to include this additional data.

Best regards
Sebastian Kapp
