### ISSUE TITLE
Local server is not connecting with application

### ISSUE THREAD

**Issue by umairarif1988** [AR-Eye-Tracking-Toolkit/ARETT#13]
Hi, Thanks for nice tutorial. I opened the applicaiton on unity 2019 and trying to connect with web server application.
I used xampp server to run server code but its shows always no connected. 
Inside application configuration: http://localhost/HTML/index.html/ i am using this address.
![image](https://user-images.githubusercontent.com/57673408/191260757-84ea6847-b4fa-4dc7-a9e3-9c36a40974f4.png)
Seconldy i put checked sign on data saving option to save file inside the deivce but i did not get any file there.
Please guide me where i am making mistake..

![image](https://user-images.githubusercontent.com/57673408/191261245-b4620dd8-1119-4866-b370-ec3fae52a8ec.png)

**Comment by sekapp** [comment]
Hi,

the webserver and control interface are running on the HoloLens device itself and do not require a separate device/server like xampp.
If you rest the "Listener Base URI" setting and all other settings you might have changed interface should work.

Inside the unity editor simply press play and then connect to the web interface using localhost: http://localhost:8080/
This should bring up the interface and you can test it as well as record simulated data (not live data from a HL2!).

When you build and run the application on the HL2, you can connect to the interface using the IP-Address of the HoloLens. (e.g., http://192.168.0.20:8080, if the IP of the HoloLens in the local network is 192.168.0.20).

Regarding your recording question: Data is only recorded if a recording is explicitly started. This can be done using the control interface or by a custom Unity script accessing the data logger (https://github.com/AR-Eye-Tracking-Toolkit/ARETT/blob/master/Scripts/DataLogger.cs#L145).
The "save file inside device" setting you reference is probably the setting where the recordings are stored. If you reset your changes (or did not change the presets) the recording should be stored in the Documents folder on the HoloLens which can be accessed e.g. via USB.

If you have any issues regarding the control interface or saving data, I recommend you first try a new Unity project and add ARETT with no changes to the default settings, as you might have unknowingly changed some settings in your current project which stops ARETT from working.

**Comment by GloriaCoboZambrana** [comment]
Hello, I am using ARETT with Unity 2021 (I update the WebServer script to be able to do this automatically loading the JavaScript files from the script). 
Thus, when I run the app, where I introduce the EyeTracking Prefab with the WebServer set by default (Listener Base URI = http://*:8080/ ), I am able to charge the control interface. 
Then, when I build the project and deploy it on my HL2 ( I change Listener Base URI as you indicated for http://192.168.0.20:8080/ but with my HL2 IP). Then, when I open the app on my HL2 (after build, and deploy successfully) the app doesn't run and the control interface neither.
I don't know if I am doing something wrong, or if I can try another thing, any advice would be appreciated. Thank you.

**Comment by sekapp** [comment]
Hi,

the Listener Base URI should usually be left as "http://*:8080/", even when deploying to the HL2. The specific IP of the HL2 is only needed to access the interface in your browser.

Sadly I'm unable to support you regarding Unity 2021. I have only worked with ARETT using Unity 2019 and personally am currently unable to test newer Unity versions.
Did you deploy and start the app using Visual Studio? If started in debug mode and with the debugger attached, you should see the console messages in Visual Studio which might indicate why the application isn't running.

**Comment by GloriaCoboZambrana** [comment]
Hi again, now that I deployed with the URI "http://*:8080/ the app runs correctly in ,y HL2. But I still not able to charge the control interface at localhost:8080.
Also, yes, I am using Visual Studio 2019 to deploy, and I try the debug mode, only see this two possible errors (?):
![image](https://user-images.githubusercontent.com/63316001/224073930-d54dda6c-5ab2-460b-852c-2f726777c7ec.png)
The one that indicates "The data area passed to a system call is too small" I think that is something related with Unity 2021 from what I've seen: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10398
And the "RPC server is unavailable" may be the source of the problem.

**Comment by sekapp** [comment]
Hi,

regarding the access to the control interface you need to do the following:
1) Leave the default "http://*:8080/" URI in the ARETT settings
2) Build and Run the app on HL2
3) While the app is running on HL2 open the browser on your PC and access http://192.168.0.20:8080/ (or the correct ip of your HL2)
Did you do/try this or are you doing something different?

You can only access the control interface with localhost if you are running ARETT on the same device. For example when running inside Unity editor while accessing the interface from the same PC. As soon as you run ARETT on a different device (e.g. HL2) you need to use the IP of that device to access the interface.

If the issue still persists I sadly won't be able to further assist you as I'm unable to identify and debug the potential RPC error in your app.

**Comment by GloriaCoboZambrana** [comment]
Hi,
I tried this, but unfortunately it still does not work.
Thank you for your help anyway

**Comment by sekapp** [comment]
Hi, maybe you can try the [Unity 2021 update](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/releases/tag/v2.0.0). While this update does not change the handling of the web server, I so far haven't received complaints regarding accessibility of the web interface on Unity 2021 with this update.
