### ISSUE TITLE
Wiki: Wrong link for control interface

### ISSUE THREAD

**Issue by turbotimon** [AR-Eye-Tracking-Toolkit/ARETT#14]
On Wiki:
https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Layers

In the sentence:
> This layer can be shown/hidden from the [control interface](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Web-Server) and ..

Points to:
https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Web-Server

Should point to:
https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Control-Interface

**Comment by turbotimon** [comment]
the same is true for further down:
> ...which can be displayed at different distances using the [control interface](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Web-Server).

**Comment by sekapp** [comment]
Thank you! I have fixed the links on this page as well as on some other wiki pages.
