### ISSUE TITLE
Issues with Windows.Storage dll referenced in FileHandlerUWP.cs?

### ISSUE THREAD

**Issue by matthew-corbett** [AR-Eye-Tracking-Toolkit/ARETT#2]
First, thank you for making this toolkit, it had made something I'm working on a ton easier.

Second, I've been trying ot figure out why my HL2 only creates the headers for the gaze data in the .csv on my HL2 but no actual data, and today, for seemingly no reason, the prefabs and scripts can no longer compile.  I get three compilation errors, all in FileHandlerUWP.cs.  

![image](https://user-images.githubusercontent.com/87574595/134243717-f3957f27-644a-4927-8ae0-9dcbc3fa115b.png)

I changed nothing since the last time I successfully built the project.  Very odd. Also, my build settings are set to UWP.  This is very strange. Any other issues like this?

**Comment by sekapp** [comment]
Nice to hear that the toolkit helps you in your work!

What version of Unity are you using and what exactly are your build settings?
The errors look to me like the build environment is configured incorrectly as the missing Windows namespace is only included in the UWP environment. However, if the build settings aren't set for UWP this should be handled by the toolkit and the UWP file handler shouldn't be included in the build if it isn't a UWP build.

Have you tried completely emptying or deleting your build folder and making a new Unity build from scratch?
The incremental building into an existing build folder sometimes breaks for me with a full rebuild from scratch being an easy fix.


Regarding the issue with only a header and no gaze data in the csv file:
Did you give the application gaze permission and also made sure that the wearer of the device has a valid eye tracking calibration? It also has to be worn to produce data, i.e. not just sitting on a table.
I have run into some issues where the HoloLens reports an existing valid calibration (and granted gaze permissions), however the calibration is actually missing resulting in no actual gaze data. As the toolkit relies on the information provided by the HoloLens to be accurate this can lead to cases as you observe where the toolkit thinks that everything is set up for recording, the HoloLens however doesn't actually provide gaze data.

**Comment by matthew-corbett** [comment]
"I have run into some issues where the HoloLens reports an existing valid calibration (and granted gaze permissions), however the calibration is actually missing resulting in no actual gaze data. As the toolkit relies on the information provided by the HoloLens to be accurate this can lead to cases as you observe where the toolkit thinks that everything is set up for recording, the HoloLens however doesn't actually provide gaze data."

How did you fix this?  Sounds alot like my situation.  I've calibrated numerous times, and have all the providers setup.  Also, I'm wearing it while I try to collect data.

**Comment by sekapp** [comment]
For me simply running the calibration again always fixed it. Maybe you can try the [eye tracking example from the MRTK](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/features/example-scenes/eye-tracking-examples-overview.md) to check if the issue is with your application/ARETT or if the HoloLens does not provide eye tracking data at all.

What version of Unity and which Windows Version on the HoloLens 2 are you using? Is the same issue present when you create a new clone of the ARETT example project on your PC and create an unmodified build?
Sadly I'm not able to further test these issues right now but maybe I can have a look at it later.
