### ISSUE TITLE
Using Timestamp

### ISSUE THREAD

**Issue by idogi124** [AR-Eye-Tracking-Toolkit/ARETT#3]
Hi, I have some questions about time stamps and I’d really appreciate your help.

1. I’m using the ARETT toolkit in unity and having problems with the time stamp. As you can see in the attached image, the time isn’t shown as HH:MM:SS, and the value isn’t changing during the testing. Any suggestions on how to fix it?

2. I’d love to know what is the time source. Is it from the computer clock itself? Will the time source change when I’ll use the toolkit on a HoloLens?

3. Do you have any recommendations on methods to sync time between the HoloLens and other PCs?

Thank you for all of your help (: 

![F09F806D-B47B-46CF-8B05-0E932432AA9B](https://user-images.githubusercontent.com/91189536/134321782-6b650fb2-925c-4452-864d-94d1c7b355eb.jpeg)

**Comment by sekapp** [comment]
Hi,

the timestamps recorded by the toolkit are saved as unix timestamp. The source of the time is from the internal clock of the HoloLens or more general the device ARETT is currently running on.
Each column is shortly described in the wiki: https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Log-Format
As the clocks of multiple devices aren't synched perfectly, the timestamps will be slightly different on each device.

There is currently no solution for syncing time between devices implemented. One option could be to send the current PC time to a running recording on a HoloLens using the information log option: https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Control-Interface#information-log
While this does not result in perfect synchronization it could enable rough synchronization and compensate for clock offsets in the region of a few seconds or minutes.

Best regards
Sebastian Kapp

**Comment by ephynes** [comment]
What is the average  timestamp difference between sensors on the HL2 in ms ?

**Comment by sekapp** [comment]
In what way do you mean _the average timestamp difference between sensors_?
If you mean the time difference between data points of the eye tracker it is given by the data rate of the eye tracker. This rate is 30 Hz in case of the HL2 resulting in ~33.33 ms time difference between each data point.
Otherwise maybe you can give more detail what you are searching for, and I will try to answer it.
