### ISSUE TITLE
Real-time observation

### ISSUE THREAD

**Issue by shogo1998** [AR-Eye-Tracking-Toolkit/ARETT#5]
In this toolkit, we can check the eye tracking information in a CSV file, but is it possible to observe it in real time?

**Comment by sekapp** [comment]
Hi,

in the default toolkit only the logging into a CSV file is implemented.
However, you can subscribe to the new data event of the [Data Provider](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Data-Provider) with your own custom script to access real time data. You can then for example stream this data to a second PC or use some other form of visualization.

Best regards
Sebastian Kapp
