### ISSUE TITLE
Can't access the Control Interface

### ISSUE THREAD

**Issue by Junee-Kim** [AR-Eye-Tracking-Toolkit/ARETT#6]
Hi,

I have some problem with accessing the Control Interface.

When I tried the demo using the Unity Editor, I changed the address in EyeTracking>WebServer>Configuration>Listener Case URI as http://127.0.0.1:8080/ and that website was accessable after I pressed the play button.

However, when I tried the SampleScene in ARETT (not Demo) in my own Hololens2 device, something went wrong. In this case I changed the address in EyeTracking>WebServer>Configuration>Listener Case URI as http://<ip_address_mydevice>:8080/, built it, and ran the app in my device. However, I couldn't access the Control Interface at "http://<ip_address_mydevice>:8080/" although it seemed that the app was running fine. I set the build target to UWP and checked the permission configuration before I built the samplescene. Is there any step that I forgot or misunderstood?

Thank you.

**Comment by sekapp** [comment]
Hi,

usually, it shouldn’t be necessary to change the base URI to access the control interface. The default `http://*:8080` (see [here](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/blob/master/Scripts/WebServer.cs#L46)) should enable you to access the interface on any network. (See [issue #1](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/issues/1#issuecomment-888368597))
Did you try the default base URI on the HoloLens 2 device? If not, can you try if this solves your issues?

Best regards
Sebastian Kapp

**Comment by Junee-Kim** [comment]
Hi,

Thanks for your fast response :)
I used the default "http://*:8080", built it, and launched the app in my Hololens2 device.
However it seems that I can't reach the Control Interface at "http://<ip_address_mydevice>:8080/".
Is there anything that I have to do after launching the app like I pressed the play button in the demo version?
Can you help me solving this problem a little bit more?

Thank you!

**Comment by sekapp** [comment]
Hi,

did you use the IP address of the HoloLens (not the PC you are accessing from) and made sure all network permissions, especially the private network permissions, are set correctly for the UWP build in Unity? Please also check the permissions in the built UWP project inside Visual Studio, sometimes changes in the permissions are not updated in the built solution.
If all these settings are correct and the URI is the default URI there might be additional issues in the project. Maybe you can also try to completely delete your current UWP build and create a new build with correct settings and permissions from unity.

Best regards
Sebastian Kapp

**Comment by Junee-Kim** [comment]
Hi,

I realized that the sample scene I was using was provided by some MRTK file, not ARETT.

**Comment by Junee-Kim** [comment]
Hi,

I realized that the sample scene I was using was provided by some MRTK file, not ARETT.
I made a new empty project to start everything from scratch, but the app didn't work well. (I could only see the 'Made in Unity logo which means it's loading endlessly..?)
The following steps are the process I had done.
If there is something wrong or missing, it will be really nice of you to let me know. I'm kind of new to Hololens2 so I'm quite clumsy :( Thanks!

1. Import MRTK files(v2.7.3) to the empty project. (Unity Version 2020.3.6f1)
2. Add XR plug-in Management>Windows Mixed Reality
3. Move files in ARETT into the Assets folder.
4. Add Eye Tracking (Prefab Asset) to the scene. (The only object existing in Hierarchy)
5. Change Build Settings to UWP.
6. Check Configuration.
7. Build.
8. Run the app in my own Hololens2.

Result : Can only see the Unity Logo, the Control Interface at "http://<ip_address_mydevice>:8080/" unaccessable.

Also this time I skipped the prior settings that Microsoft tells us to do (https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/input/eye-tracking/eye-tracking-basic-setup?view=mrtkunity-2021-05) unlike before. (Would this be necessary..?)

**Comment by sekapp** [comment]
Hi,

I have only tested ARETT with Unity 2019.4, not Unity 2020. It might be possible that changes are required for ARETT to work with Unity 2020. I have previously received some feedback that in theory ARETT seems to work but there are issues with the eye-tracking calibration, probably due to the changes in the XR plug-in system. Sadly, I'm unable to verify or update ARETT for Unity 2020 at the moment and therefore am unable to help you further.

Do you need to use Unity 2020 for your projects? If not, maybe you can try to use Unity 2019.

Best regards
Sebastian Kapp
