### ISSUE TITLE
Connecting Control Interface with Unity scene

### ISSUE THREAD

**Issue by Mattiademasi** [AR-Eye-Tracking-Toolkit/ARETT#9]
Hi Sebastian, thank you for the amazing work you have done.
I would like to push your work a bit further by connecting the elements in the Control Interface with elements in the Unity scene.

Specifically, I am trying to select/press my Start button in the scene when I press Start Recording in the Control Interface.

Do you think this is something possible to do with the actual version of ARETT?
Any idea on how to implement it?

Thank you,
Mattia

**Comment by serhangul** [comment]
Hi Mattia, I think it should be possible by linking `dataLogger.StartRecording` to your button in the Unity scene. There is a nice HL2 tutorial on how to use MRTK to add interaction/buttons to your scene, you might want to check that:
https://docs.microsoft.com/en-us/learn/modules/get-started-with-object-interaction/

**Comment by Mattiademasi** [comment]
Thank you for the quick response.
So, I am able to start logging clicking on the button in my scene, which triggers the start logging also in the Control Interface.
I was wondering if it was possible do the same thing, but in the opposite direction (clicking on Start Logging in the Control interface to trigger the button in the Unity Scene).

**Comment by sekapp** [comment]
Hi, the `dataLogger.FileHandler.writingData` flag indicates if a recording is currently active. You could check this flag in a script and update the button accordingly.

**Comment by Mattiademasi** [comment]
Thank you! It worked!
